export const source = [
    { nomeLavorazione: "LavorazioneA", tariffa: 1, unita: "cad", tipo: "MT", tempoQuantita: 0, costoUn: 10 },
    { nomeLavorazione: "LavorazioneB", tariffa: 2, unita: "a corpo", tipo: "MDO", tempoQuantita: 0, costoUn: 234.56 },
    { nomeLavorazione: "LavorazioneC", tariffa: 3, unita: "h", tipo: "MDO", tempoQuantita: 0, costoUn: 345.67 },
    { nomeLavorazione: "LavorazioneD", tariffa: 4, unita: "cad", tipo: "MT", tempoQuantita: 0, costoUn: 456.78 },
    { nomeLavorazione: "LavorazioneE", tariffa: 5, unita: "h", tipo: "MDO", tempoQuantita: 0, costoUn: 78.90 },
    { nomeLavorazione: "LavorazioneF", tariffa: 6, unita: "a corpo", tipo: "MDO", tempoQuantita: 0, costoUn: 89.01 },
    { nomeLavorazione: "LavorazioneG", tariffa: 7, unita: "cad", tipo: "MT", tempoQuantita: 0, costoUn: 90.12 },
    { nomeLavorazione: "LavorazioneH", tariffa: 8, unita: "h", tipo: "MDO", tempoQuantita: 0, costoUn: 101.23 },
    { nomeLavorazione: "LavorazioneI", tariffa: 9, unita: "a corpo", tipo: "MDO", tempoQuantita: 0, costoUn: 112.34 },
    { nomeLavorazione: "LavorazioneJ", tariffa: 10, unita: "cad", tipo: "MT", tempoQuantita: 0, costoUn: 123.45 },
    { nomeLavorazione: "LavorazioneK", tariffa: 11, unita: "cad", tipo: "MT", tempoQuantita: 0, costoUn: 134.56 },
    { nomeLavorazione: "LavorazioneL", tariffa: 12, unita: "a corpo", tipo: "MDO", tempoQuantita: 0, costoUn: 145.67 },
    { nomeLavorazione: "LavorazioneM", tariffa: 13, unita: "h", tipo: "MDO", tempoQuantita: 0, costoUn: 156.78 },
    { nomeLavorazione: "LavorazioneN", tariffa: 14, unita: "cad", tipo: "MT", tempoQuantita: 0, costoUn: 167.89 },
    { nomeLavorazione: "LavorazioneO", tariffa: 15, unita: "h", tipo: "MDO", tempoQuantita: 0, costoUn: 178.90 },
    { nomeLavorazione: "LavorazioneP", tariffa: 16, unita: "a corpo", tipo: "MDO", tempoQuantita: 0, costoUn: 189.01 },
    { nomeLavorazione: "LavorazioneQ", tariffa: 17, unita: "cad", tipo: "MT", tempoQuantita: 0, costoUn: 190.12 },
    { nomeLavorazione: "LavorazioneR", tariffa: 18, unita: "h", tipo: "MDO", tempoQuantita: 0, costoUn: 201.23 },
    { nomeLavorazione: "LavorazioneS", tariffa: 19, unita: "a corpo", tipo: "MDO", tempoQuantita: 0, costoUn: 212.34 },
    { nomeLavorazione: "LavorazioneT", tariffa: 20, unita: "cad", tipo: "MT", tempoQuantita: 0, costoUn: 223.45 },
    { nomeLavorazione: "LavorazioneU", tariffa: 21, unita: "cad", tipo: "MT", tempoQuantita: 0, costoUn: 234.56 },
    { nomeLavorazione: "LavorazioneV", tariffa: 22, unita: "a corpo", tipo: "MDO", tempoQuantita: 0, costoUn: 245.67 },
    { nomeLavorazione: "LavorazioneW", tariffa: 23, unita: "h", tipo: "MDO", tempoQuantita: 0, costoUn: 256.78 },
    { nomeLavorazione: "LavorazioneX", tariffa: 24, unita: "cad", tipo: "MT", tempoQuantita: 0, costoUn: 267.89 },
    { nomeLavorazione: "LavorazioneY", tariffa: 25, unita: "h", tipo: "MDO", tempoQuantita: 0, costoUn: 278.90 },
    { nomeLavorazione: "LavorazioneZ", tariffa: 26, unita: "a corpo", tipo: "MDO", tempoQuantita: 0, costoUn: 289.01 },
    { nomeLavorazione: "LavorazioneAA", tariffa: 27, unita: "cad", tipo: "MT", tempoQuantita: 0, costoUn: 290.12 },
    { nomeLavorazione: "LavorazioneBB", tariffa: 28, unita: "cad", tipo: "MT", tempoQuantita: 0, costoUn: 301.23 },
    { nomeLavorazione: "LavorazioneCC", tariffa: 29, unita: "a corpo", tipo: "MDO", tempoQuantita: 0, costoUn: 312.34 },
    { nomeLavorazione: "LavorazioneDD", tariffa: 30, unita: "h", tipo: "MDO", tempoQuantita: 0, costoUn: 323.45 },
    { nomeLavorazione: "LavorazioneEE", tariffa: 31, unita: "cad", tipo: "MT", tempoQuantita: 0, costoUn: 334.56 },
    { nomeLavorazione: "LavorazioneFF", tariffa: 32, unita: "h", tipo: "MDO", tempoQuantita: 0, costoUn: 345.67 },
    { nomeLavorazione: "LavorazioneGG", tariffa: 33, unita: "a corpo", tipo: "MDO", tempoQuantita: 0, costoUn: 356.78 },
    { nomeLavorazione: "LavorazioneHH", tariffa: 34, unita: "cad", tipo: "MT", tempoQuantita: 0, costoUn: 367.89 },
    { nomeLavorazione: "LavorazioneII", tariffa: 35, unita: "h", tipo: "MDO", tempoQuantita: 0, costoUn: 378.90 },
    { nomeLavorazione: "LavorazioneJJ", tariffa: 36, unita: "a corpo", tipo: "MDO", tempoQuantita: 0, costoUn: 389.01 },
    { nomeLavorazione: "LavorazioneKK", tariffa: 37, unita: "cad", tipo: "MT", tempoQuantita: 0, costoUn: 390.12 },
    { nomeLavorazione: "LavorazioneLL", tariffa: 38, unita: "cad", tipo: "MT", tempoQuantita: 0, costoUn: 401.23 },
    { nomeLavorazione: "LavorazioneMM", tariffa: 39, unita: "a corpo", tipo: "MDO", tempoQuantita: 0, costoUn: 412.34 },
    { nomeLavorazione: "LavorazioneNN", tariffa: 40, unita: "h", tipo: "MDO", tempoQuantita: 0, costoUn: 423.45 },
    { nomeLavorazione: "LavorazioneOO", tariffa: 41, unita: "cad", tipo: "MT", tempoQuantita: 0, costoUn: 434.56 },
    { nomeLavorazione: "LavorazionePP", tariffa: 42, unita: "h", tipo: "MDO", tempoQuantita: 0, costoUn: 445.67 },
    { nomeLavorazione: "LavorazioneQQ", tariffa: 43, unita: "a corpo", tipo: "MDO", tempoQuantita: 0, costoUn: 456.78 },
    { nomeLavorazione: "LavorazioneRR", tariffa: 44, unita: "cad", tipo: "MT", tempoQuantita: 0, costoUn: 467.89 },
    { nomeLavorazione: "LavorazioneSS", tariffa: 45, unita: "cad", tipo: "MT", tempoQuantita: 0, costoUn: 478.90 },
    { nomeLavorazione: "LavorazioneTT", tariffa: 46, unita: "a corpo", tipo: "MDO", tempoQuantita: 0, costoUn: 489.01 },
    { nomeLavorazione: "LavorazioneUU", tariffa: 47, unita: "h", tipo: "MDO", tempoQuantita: 0, costoUn: 490.12 },
    { nomeLavorazione: "LavorazioneVV", tariffa: 48, unita: "cad", tipo: "MT", tempoQuantita: 0, costoUn: 401.23 },
    { nomeLavorazione: "LavorazioneWW", tariffa: 49, unita: "h", tipo: "MDO", tempoQuantita: 0, costoUn: 412.34 },
    { nomeLavorazione: "LavorazioneXX", tariffa: 50, unita: "a corpo", tipo: "MDO", tempoQuantita: 0, costoUn: 423.45 }
  ];